### ISSUE TITLE
Documentation URLs direct to 404

### ISSUE THREAD

**Issue by Daniel528** [hyochan/react-native-iap#2864]
**Description**

The two links I've found for the documentation [https://react-native-iap.dooboolab.com/](https://react-native-iap.dooboolab.com/) and [https://react-native-iap.hyochan.dev/](https://react-native-iap.hyochan.dev/) both direct to 404.

**Expected Behavior**

The documentation should open

**Comment by hyochan** [comment]
It is https://react-native-iap.hyo.dev ! Sorry for inconvenience
