### ISSUE TITLE
iOS: Purchase failed [Error: No products available]

### ISSUE THREAD

**Issue by alessiapacca** [hyochan/react-native-iap#2865]
Hi! 
I am using react-native-iap for purchasing credits in my iOS app.
Simple code to get the product: 

```
await RNIap.initConnection();
console.log("IAP initialized");
const products: RNIap.Product[] = await RNIap.getProducts({skus: [environmentService.productIDInAppPurchase]});
console.log("Products:", products);
const purchaseUpdateSubscription = RNIap.purchaseUpdatedListener(
        async (purchase: RNIap.Purchase) => {....
```

the product ID is correct, I checked multiple times. However this prints:  
IAP initialized  
Products: []
ERROR  Purchase failed [Error: No products available]

The in-app-purchase on app store connect is still "under review" but they rejected my build because they said they cannot try the iap. Any suggestion of where the issue may be?

**Comment by sn-will** [comment]
I'm having the same issue here, my products are not being listed.

I'm wondering if this is related to the STORE_KIT version.

**Comment by sn-will** [comment]
@alessiapacca Check if your "Paid Apps Agreement" on App Store Connect are active:

![image](https://github.com/user-attachments/assets/207b8971-af27-4d6b-b104-49d4531f9241)

**Comment by alessiapacca** [comment]
@sn-will both of the agreements are active for my app

**Comment by alessiapacca** [comment]
Update: it was not the agreements, however I had to fill up more banking information!
After a while they got processed and now it works!
