### ISSUE TITLE
Type mismatch: inferred type is String? but String was expected

### ISSUE THREAD

**Issue by nes123** [hyochan/react-native-iap#2871]
I get the following error:
java/com/dooboolab/RNIap/PromiseUtlis.kt:40:21 Type mismatch: inferred type is String? but String was expected

**Environment:**

- react-native-iap: 12.15.6
- react-native: 0.76
- Platforms (iOS, Android, emulator, simulator, device): android

**Comment by sontruongna** [comment]
Same here

**Comment by mlazari** [comment]
Hi, I opened a PR here: https://github.com/hyochan/react-native-iap/pull/2872
In the meantime you can use this [patch](https://www.npmjs.com/package/patch-package):
[react-native-iap+12.15.6.patch](https://github.com/user-attachments/files/17540061/react-native-iap%2B12.15.6.patch)

**Comment by dmk3141618** [comment]
Same error.

It seems critical error. When will it be updated in the official version?

**Comment by dmk3141618** [comment]
It worked after applying the fix! Thank you for your great work.

     try {
-        this.reject(code, message, throwable)
+        this.reject(code ?: "", message, throwable)
     } catch (oce: ObjectAlreadyConsumedException) {
         Log.d(TAG, "Already consumed ${oce.message}")
     }

fun Promise.safeReject(
    code: String?,
    message: String?,
    throwable: Throwable?,
) {
    try {
        this.reject(code ?: "", message, throwable)
    } catch (oce: ObjectAlreadyConsumedException) {
        Log.d(TAG, "Already consumed ${oce.message}")
    }
}
